### ISSUE TITLE
[BUG] Invalid GitHub links

### ISSUE THREAD

**Issue by Panquesito7** [Design-and-Code/Opensource-practice#36]
**Description**

There seem to be a few people's names that lead to GitHub's homepage, or a few other links that are invalid.
Those should be fixed immediately. If you want to know their usernames, we can check the owners of the PR.

For the invalid links, we could ask them directly or remove them.

**Additional information**

None.

**Comment by muditchoudhary** [comment]
Hey I would like to work on this.

But I have a question are you talking about the main readme file here? In that file some people's name link point to an invalid/GitHub homepage, right?

**Comment by Panquesito7** [comment]
> Hey, @Panquesito7 I would like to work on this.
>
> But I have a question are you talking about the main readme file here? In that file some people's name link point to an > invalid/GitHub homepage, right?

Yep, that's the error. 🙂

**Comment by muditchoudhary** [comment]
Hey, @Panquesito7  does this issue also count for the hacktoberfest? just want to clarify.

**Comment by Panquesito7** [comment]
> Hey, @Panquesito7 does this issue also count for the hacktoberfest? just want to clarify.

It should, IMO.

**Comment by muditchoudhary** [comment]
Hey, @Panquesito7 I found problems with the names of these people. I've fixed all the broken links except for 2 folks, 1 is Anirudha Das 2 is Hardik Jaiswal. I could not find their correct[latest] user names on Closed PRs. So what should I do next? 

Should I raise my pull request?

![image](https://user-images.githubusercontent.com/74391865/193496255-43f1e1f5-9990-46e3-bd39-5966a103ef30.png)

**Comment by Panquesito7** [comment]
> Hey, @Panquesito7 I found problems with the names of these people. I've fixed all the broken links except for 2 folks, 1 is Anirudha Das 2 is Hardik Jaiswal. I could not find their correct[latest] user names on Closed PRs. So what should I do next?
> 
> Should I raise my pull request?
> 
> ![image](https://user-images.githubusercontent.com/74391865/193496255-43f1e1f5-9990-46e3-bd39-5966a103ef30.png)

Hmm. I will ask the staff from the Discord server and see if they know any of them.
Ping me in a few days in case I don't make any comment here. Thank you. 🙂

**Comment by muditchoudhary** [comment]
Hey, @Panquesito7 this issue did not count for the hacktoberfest. Maybe a label is also necessary? Is it possible to add a label now?

Thanks :)

**Comment by Prithvi2310** [comment]
Is this issue still open?
